



try:
  print(12/2)
except Exception as e:
    print(e)
